# model/config.py
"""
Centralized configuration for Trajecto trajectory estimation models.

IMPORTANT: To regenerate computed statistics, run:
    python utils/compute_config_statistics.py

This will recompute velocity and innovation statistics from the dataset.
"""

class Config:
    """Configuration class for trajectory estimation models."""

    # --- Global Training Parameters ---
    TARGET_SAMPLING_RATE_HZ = 50.107  # Target sampling rate (Hz) for data acquisition and model
    DT = 1.0 / TARGET_SAMPLING_RATE_HZ  # Time delta (s) for model integration (50.107 Hz = 0.019957291396 s)
    INITIAL_PEN_TIP_OFFSET = [0.0, -0.06, 0.0] # [x, y, z] offset from IMU to pen tip (m)

    # --- Dataset Parameters ---
    DATASET_H5_PATH = "./data/dataset.h5"
    VALIDATION_DATASET_H5_PATH = "./data/dataset.h5"
    AUGMENT_MULTIPLIER = 40
    SUBSAMPLE_STEP = 1
    DO_AUGMENT = True
    YAW_ANGLE = (-0.78, 0.78)   # Set small angle in first and increase when fine tunning.
    SIGMA_TILT = 0.02           # Same ( Don't increase too large (0.02 ~ 0.52))
    SCALER_STATS_H5_PATH = "./data/scaler_stats.h5"

    # --- ZUPT Parameters (used by ESKF and AEKF) ---
    ZUPT_WINDOW_SIZE = 20
    ZUPT_ACCEL_THRESHOLD = 0.1430  # Optimized from GT analysis: 92% ZUPT coverage, 51% moving rejection (was: 0.5)
    ZUPT_FORCE_VAR_THRESHOLD = 36660  # Optimized from GT analysis: 90% ZUPT coverage, 18% moving rejection (was: 100000)
    ZUPT_FORCE_DELTA_THRESHOLD = 154  # Optimized from GT analysis: 87% ZUPT coverage, 20% moving rejection (was: 2000)

    # --- Allan Variance Noise Parameters (used by ESKF and AEKF) ---

    # Base values from Allan variance analysis (empirical measurements)
    ARW_X, ARW_Y, ARW_Z = 7.1664e-04, 7.9283e-04, 7.5335e-04
    GYRO_BI_X, GYRO_BI_Y, GYRO_BI_Z = 1.6441e-04, 2.8196e-04, 1.2203e-04
    VRW_X, VRW_Y, VRW_Z = 8.3297e-03, 6.7196e-03, 9.3271e-03
    ACCEL_BI_X, ACCEL_BI_Y, ACCEL_BI_Z = 4.3723e-03, 1.7697e-03, 2.8099e-03

    # --- Physical Constants ---
    GRAVITY_MAGNITUDE = 9.80665  # Standard gravity (m/s²)

    # =========================================================================
    # COMPUTED STATISTICS (Generated by utils/compute_config_statistics.py)
    # =========================================================================
    # To regenerate: python utils/compute_config_statistics.py
    # Dataset: data/dataset.h5 (42 samples, 12,600 timesteps)
    # Last updated: 2026-01-05
    # =========================================================================

    # --- Velocity Statistics ---
    # Per-axis mean and standard deviation from ground truth velocities (WORLD frame)
    # NOTE: VEL_MEAN is NOT used for body-frame velocity normalization (frame mismatch)
    #       Only VEL_STD is used for scaling body-frame velocities
    VEL_MEAN = [0.013089556969932, -0.008355271130136, -0.000882682535667]  # m/s [x, y, z] - WORLD frame (diagnostic only)
    VEL_STD = [0.111915624833814, 0.102708548431423, 0.010636343964785]     # m/s [x, y, z] - used for BODY frame scaling
    VEL_STD_L2 = 0.152273716759559  # L2 norm of std vector (m/s)

    # Velocity correction scale (2σ for ~95% coverage, ISOTROPIC)
    # Used to denormalize TCN velocity correction output: tanh(output) * VEL_CORRECTION_SCALE
    # Isotropic scaling preserves directional accuracy across all axes
    VEL_CORRECTION_SCALE = 0.304547433519118  # m/s (isotropic)

    # --- Innovation Normalization ---
    # Innovation is normalized using Allan variance (VRW/ARW) from theoretical sensor noise.
    # See VRW_X, VRW_Y, VRW_Z (accel) and ARW_X, ARW_Y, ARW_Z (gyro) above.
    # Normalization: innovation / max(VRW) for accel, innovation / max(ARW) for gyro (isotropic).
    # This approach is theoretically principled and avoids drift-contaminated empirical statistics.

    # --- Model Specific Parameters ---
    class ESKFTCN:
        TCN_INPUT_SIZE = 19
        TCN_CHANNELS = [64, 64, 64, 64]
        KERNEL_SIZE = 5
        DROPOUT = 0.1
        TCN_DILATION_FACTORS = [1, 4, 8, 16] # Added TCN Dilation Factors
        USE_ZUPT = False  # Classic threshold-based ZUPT disabled (TCN handles ZUPT detection)
        USE_TCN_ZUPT = True  # TCN predicts zupt_prob directly from physics features
        ADAPTIVE_GAIN_ESKF = 0.5 # Specific to ESKF's R adaptivity
        # Initial standard deviation for ZUPT measurement noise in ESKF.
        ZUPT_NOISE_STD_ESKF = [0.01, 0.01, 0.01]
        # Hard velocity reset threshold: when zupt_prob >= this value, directly set velocity to zero
        ZUPT_HARD_RESET_THRESHOLD = 0.98
        # Whether to use Depthwise Separable Convolutions in TCN for ESKFTCN.
        USE_SEPARABLE_CONV = False
        # Mahalanobis distance threshold for measurement gating (Chi-square dist, dof=6, p=0.99 => ~16.8)
        MAHALANOBIS_GATE_THRESHOLD = 16.8
        # Hard clipping range for TCN velocity correction output (m/s)
        VEL_CORR_CLIP_RANGE = 5.0

    class AEKFTCN:
        TCN_INPUT_SIZE = 19  # Reduced from 20: removed zupt_flag to avoid circular dependency
        TCN_OUTPUT_SIZE = 3 # Only predict 3D velocity residual
        TCN_NUM_CHANNELS = [64, 64, 64, 64]
        TCN_KERNEL_SIZE = 3
        TCN_DROPOUT = 0.2
        TCN_DILATION_FACTORS = [1, 2, 4, 8] # Added TCN Dilation Factors
        ADAPTIVE_R_FACTOR_AEKF = 0.1 # Specific to AEKF's R adaptivity
        ZUPT_R_FACTOR_AEKF = 1e-6 # Specific to AEKF's ZUPT R
        # Initial standard deviation for ZUPT measurement noise in AEKF.
        ZUPT_NOISE_STD_AEKF = [0.01, 0.01, 0.01]
        # Whether to use Depthwise Separable Convolutions in TCN for AEKFTCN.
        USE_SEPARABLE_CONV = False


    class OnlyTCN:
        INPUT_SIZE = 7
        OUTPUT_SIZE = 3
        TCN_CHANNELS = [64, 64, 64, 64] # Default for OnlyTCN
        KERNEL_SIZE = 3
        DROPOUT = 0.1

    # --- Loss Parameters ---
    class LOSS:
        REG_WEIGHT_ESKF_TCN = 1e-4
        REG_WEIGHT_AEKF_TCN = 1e-5
        # No specific reg weight for OnlyTCN in current loss setup