# Trajecto: Real-time 3D Trajectory Reconstruction System
# Copyright 2025-2026 Eunkyum Kim <nemonanconcode@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# NOTICE: This software is protected under the following ROK Patent Applications:
# 1. Hybrid ESKF-Stateful TCN Architecture (No. 10-2025-0201093)
# 2. 3D Ground Truth Generation via Hovering Signal Engineering (No. 10-2025-0201092)
#
# Commercial use or redistribution of the core logic requires a separate license.
# For inquiries, contact: nemonanconcode@gmail.com

# model/config.py
"""
Centralized configuration for Trajecto trajectory estimation models.

IMPORTANT: To regenerate computed statistics, run:
    python utils/compute_config_statistics.py

This will recompute velocity and innovation statistics from the dataset.
"""

class Config:
    """Configuration class for trajectory estimation models."""

    # --- Data Paths ---
    DATASET_H5_PATH = "data/dataset.h5"
    VALIDATION_DATASET_H5_PATH = "data/validation_dataset.h5"
    SCALER_STATS_H5_PATH = "data/scaler_stats.h5"

    # --- Global Training Parameters ---
    TARGET_SAMPLING_RATE_HZ = 50.107  # Target sampling rate (Hz) for data acquisition and model
    DT = 1.0 / TARGET_SAMPLING_RATE_HZ  # Time delta (s) for model integration (50.107 Hz = 0.019957291396 s)
    INITIAL_PEN_TIP_OFFSET = [0.0, -0.06, 0.0] # [x, y, z] offset from IMU to pen tip (m), check IMU's Axis from Datasheet

    # --- Data Augmentation Parameters ---
    YAW_RANGE = (-0.78, 0.78)   # Set small angle in first and increase when fine tunning.
    SIGMA_TILT = 0.02           # Same ( Don't increase too large (0.02 ~ 0.52))

    # --- ZUPT Parameters (used by ESKF) ---
    ZUPT_WINDOW_SIZE = 20
    ZUPT_ACCEL_THRESHOLD = 0.1430  # Optimized: 92% ZUPT coverage, 51% moving rejection
    ZUPT_FORCE_VAR_THRESHOLD = 36660  # Optimized: 90% ZUPT coverage, 18% moving rejection
    ZUPT_FORCE_DELTA_THRESHOLD = 154  # Optimized: 87% ZUPT coverage, 20% moving rejection

    # --- Allan Variance Noise Parameters (used by ESKF) ---

    # Base values from Allan variance analysis (empirical measurements)
    ARW_X, ARW_Y, ARW_Z = 7.1664e-05, 7.9283e-05, 7.5335e-05
    GYRO_BI_X, GYRO_BI_Y, GYRO_BI_Z = 1.6441e-05, 2.8196e-05, 1.2203e-05
    VRW_X, VRW_Y, VRW_Z = 8.3297e-04, 6.7196e-04, 9.3271e-04
    ACCEL_BI_X, ACCEL_BI_Y, ACCEL_BI_Z = 4.3723e-04, 1.7697e-04, 2.8099e-04

    # --- Physical Constants ---
    GRAVITY_MAGNITUDE = 9.80665  # Standard gravity (m/s²)

    # =========================================================================
    # COMPUTED STATISTICS (Generated by utils/compute_config_statistics.py)
    # =========================================================================
    # To regenerate: python utils/compute_config_statistics.py
    # Dataset: data/dataset.h5 (42 samples, 12,600 timesteps)
    # Last updated: 2026-01-20
    # =========================================================================

    # --- Velocity Statistics (from ground truth) ---
    # L2 norm of per-axis velocity std, used for isotropic body-frame normalization
    VEL_STD_L2 = 0.0994355743293535  # m/s

    # Velocity correction scale for log1p activation
    # With log1p: output = sign(x) * log1p(|x|) * scale
    # To achieve 0.3 m/s correction: log1p(raw) * scale = 0.3
    # With raw=2.0 (typical network output): log1p(2) ≈ 1.1, so scale ≈ 0.27
    # Increased to 0.5 to allow larger corrections with moderate raw outputs
    # Raw=1 → 0.35 m/s, Raw=3 → 0.69 m/s, Raw=5 → 0.90 m/s
    VEL_CORRECTION_SCALE = 0.5  # m/s (tuned for log1p activation)

    # --- Feature Normalization Constants ---
    # Innovation clamp range: prevents gyro innovation from exploding (can reach 100+)
    # Clamped to [-10, +10] to match z-score feature range while preserving signal
    INNOVATION_CLAMP_RANGE = 10.0

    # Gravity normalization scale: unit-normalized gravity is in [-1, +1]
    # Z-score features are typically in [-3, +3], so scale by 2.0 to match
    GRAVITY_NORM_SCALE = 2.0

    # --- Innovation Normalization ---
    # Innovation is normalized using Allan variance (VRW/ARW) from theoretical sensor noise.
    # See VRW_X, VRW_Y, VRW_Z (accel) and ARW_X, ARW_Y, ARW_Z (gyro) above.
    # Normalization: innovation / max(VRW) for accel, innovation / max(ARW) for gyro (isotropic).
    # This approach is theoretically principled and avoids drift-contaminated empirical statistics.

    # --- Model Specific Parameters ---
    class ESKFTCN:
        # TCN Architecture
        TCN_INPUT_SIZE = 16

        # TCN Update Stride (12.5Hz = stride 4 at 50Hz base rate)
        # Run TCN every N timesteps (both training and inference)
        # ESKF physics still runs at full 50Hz rate
        TCN_UPDATE_STRIDE = 4
        TCN_CHANNELS = [96, 96, 96, 96]
        KERNEL_SIZE = 3
        DROPOUT = 0.15
        # Split dilations for Y-branch architecture
        TCN_BACKBONE_DILATIONS = [1, 2]
        TCN_DYNAMIC_DILATIONS = [1, 2]
        TCN_STATIC_DILATIONS = [4, 8]
        USE_SEPARABLE_CONV = False

        # Make more directed dilation factors, current system see 39/50 ->  0.78s ( it may be little tight... )

        # --- ESKF Noise Parameters (centralized for Python & C++ parity) ---
        # ZUPT measurement noise std (m/s) - used when applying zero-velocity constraint
        ZUPT_NOISE_STD = 0.01
        # TCN velocity correction noise std (m/s) - base noise for TCN pseudo-measurements
        TCN_VEL_NOISE_STD = 0.05
        # Mahalanobis distance threshold for outlier rejection in IMU update
        # Chi-squared 6-DOF 95% = 12.59, 99% = 16.81; using 8.0 for tighter gating
        # we suggests high threshold, this is just a fail safe not a performancer.
        MAHALANOBIS_GATE_THRESHOLD_IMU = 8.0
        # ZUPT hard reset threshold - directly zero velocity when zupt_prob >= this
        ZUPT_HARD_RESET_THRESHOLD = 0.98

        # ZUPT Configuration
        USE_ZUPT = False  # Classic threshold-based ZUPT
        USE_TCN_ZUPT = True  # TCN-predicted ZUPT
        ZUPT_NOISE_STD_ESKF = [0.01, 0.01, 0.01]  # Legacy: per-axis (use ZUPT_NOISE_STD instead)
        # Gradual velocity decay parameters (replaces hard reset)
        # decay_weight = clamp((zupt_prob - onset) / (1 - onset), 0, 1) ^ exponent
        ZUPT_DECAY_ONSET = 0.5      # Start decay when zupt_prob > this value
        ZUPT_DECAY_EXPONENT = 2.0   # Quadratic decay for smooth onset

        # Filter Parameters
        ADAPTIVE_GAIN_ESKF = 0.5
        MAHALANOBIS_GATE_THRESHOLD = 30
        VEL_CORR_CLIP_RANGE = 5.0
        MAX_COVARIANCE_VAL = 2.95  # softplus(2.95) ≈ 3.0
        
        # TCN Output Head Bounds
        ZUPT_PROB_THRESHOLD = 0.5   # Probability above which we consider the pen stationary
        R_MIN = 1e-4                # Minimum measurement noise (prevents filter overconfidence)
        R_MAX = 3.0                 # Maximum measurement noise (trust floor)

        # ESKF Learnable Parameters (BPTT Control)
        # Set to False to disable backpropagation through ESKF parameters for faster training
        # This makes R_diag, zupt_noise_std, and virtual_meas_weights fixed (non-learnable)
        ESKF_LEARNABLE_PARAMS = False

        # Virtual Measurement Correction Weights (for blind period / pure ESKF mode)
        # These are learnable but initialized from Allan variance ratios:
        #   orientation_weight ∝ 1/ARW (need stronger correction for noisier gyro)
        #   gyro_bias_weight ∝ 1/GYRO_BI (stronger for faster-drifting bias)
        #   accel_bias_weight ∝ 1/ACCEL_BI
        # Computed: ARW_mean ≈ 7.5e-4, GYRO_BI_mean ≈ 1.9e-4, ACCEL_BI_mean ≈ 2.9e-3
        # Ratios normalized to ~10x baseline for numerical stability
        VIRTUAL_MEAS_WEIGHT_ORIENTATION = 13.3  # 1/(ARW_mean * 100)
        VIRTUAL_MEAS_WEIGHT_GYRO_BIAS = 5.3     # 1/(GYRO_BI_mean * 1000)
        VIRTUAL_MEAS_WEIGHT_ACCEL_BIAS = 3.4    # 1/(ACCEL_BI_mean * 100)

        # Gravity alignment for attitude correction
        USE_GRAVITY_ALIGNMENT = True
        # R scaling: during ZUPT, R = TCN_R * (STATIC/DYNAMIC)
        GRAVITY_R_STATIC = 0.01
        GRAVITY_R_DYNAMIC = 10.0  # Increased from 1.0: reduce trust in TCN gravity during motion
        # Gating thresholds for accel magnitude (m/s²)
        GRAVITY_ACCEL_MIN = 8.0
        GRAVITY_ACCEL_MAX = 12.0
        # Gravity alignment warmup: disable for first N epochs to let TCN stabilize
        GRAVITY_WARMUP_EPOCHS = 5

        # --- Quantization-Aware Training (QAT) ---
        QAT_ENABLED = False  # Toggle QAT during training
        QAT_BACKEND = "qnnpack"  # "qnnpack" for ARM, "fbgemm" for x86
        QAT_START_EPOCH = 10  # Start QAT after N epochs of FP32 warmup

        # --- Block-Parallel Scan Configuration ---
        # Accelerates covariance propagation using associative scan
        # P[t+1] = F @ P[t] @ F^T + Q computed in O(log T) parallel depth
        USE_BLOCK_PARALLEL = True  # Enable parallel covariance computation
        BLOCK_SIZE = 64  # Block size for blocked parallel scan
        USE_DOUBLE_PRECISION = False  # Use float64 for scan (better stability, slower)

        # --- Device Optimization Configuration ---
        # Hybrid CPU/GPU mode: Run sequential nominal state on CPU, parallel P scan on GPU
        # This avoids GPU kernel launch overhead for O(1) ops while leveraging GPU for batched matmul
        CPU_STATE_PROPAGATION = True  # Run nominal state propagation on CPU
        CPU_STATE_PROPAGATION_BATCH_THRESHOLD = 1  # Min batch size to use CPU path (1 = always)

    # --- Loss Parameters ---
    class LOSS:
        REG_WEIGHT_ESKF_TCN = 1e-4  # Increased from 1e-7 to prevent TCN overfitting

        # Gradient Conflict Resolution (Mutual Exclusivity)
        USE_MUTUAL_EXCLUSIVITY = True  # Enable structural gradient conflict resolution
        MAGNITUDE_MOVING_THRESHOLD = 0.01  # 10 mm/s - apply magnitude loss only above this
        ZUPT_STATIC_THRESHOLD = 0.005  # 5 mm/s - apply ZUPT loss only below this
        # Dead zone: 0.005 < vel < 0.01 reduces vel↔zupt gradient conflicts

        # FFT Loss Configuration
        USE_FFT_WINDOWING = True  # Apply Hann window to reduce spectral artifacts

        # Context-Aware Direction Loss Configuration
        GYRO_SENSITIVITY = 2.0  # Scaling factor for gyro magnitude
        MAX_CONTEXT_WEIGHT = 3.0  # Cap to prevent extreme amplification (was unlimited 7x+)
        # Example: gyro=1 rad/s → weight=3.0 (capped), gyro=0.5 → weight=2.0

        # Initial loss weights (used before DWA warmup or as fallback)
        INITIAL_MAG_WEIGHT = 1.0
        INITIAL_COS_WEIGHT = 1.0
        INITIAL_ZUPT_WEIGHT = 0.5
        INITIAL_COV_WEIGHT = 0.1  # Increased from 0.01 to reduce disparity
        INITIAL_FFT_WEIGHT = 0.5

    # === Simulated Data Configuration ===
    class SIMDATA:
        DEFAULT_PATH = "data/simulated_dataset.h5"
        DEFAULT_MIX_RATIO = 0.8  # Ratio of sim data in mixed training

    # === Two-Stage Training Configuration ===
    class TWO_STAGE:
        # Stage 1: Sim pretrain (ESKF frozen)
        STAGE1_EPOCHS = 150
        STAGE1_LR = 1e-3
        STAGE1_BATCH_SIZE = 64
        STAGE1_ESKF_LEARNABLE = False

        # Stage 2: Mixed fine-tune (ESKF unfrozen)
        STAGE2_EPOCHS = 50
        STAGE2_TCN_LR = 1e-5
        STAGE2_ESKF_LR = 1e-6
        STAGE2_BATCH_SIZE = 16
        STAGE2_MIX_RATIO = 0.8

    # === Delta Loss (Semi-Loop Closure) ===
    class DELTA_LOSS:
        ENABLED = True
        WINDOW_SIZES = [25, 100]  # timesteps (0.5s, 2s, 5s @ 50Hz)
        WINDOW_WEIGHTS = [0.3, 0.4]
        STRIDE = 10
        WEIGHT = 0.5  # Fixed weight, not affected by DWA

    # === Motion Detection & Initialization ===
    class MOTION:
        """Thresholds for motion/static detection and initialization."""
        # ESKF Initialization
        INIT_STATIC_MIN_S = 2.0  # seconds
        INIT_MIN_SAMPLES = 20    # Minimum samples for reliable covariance/bias estimation
        INIT_GYRO_VAR_THRESHOLD = 0.002  # rad²/s²
        INIT_ACCEL_RELIABLE_MIN = 4.9    # m/s² (~0.5g)
        INIT_ACCEL_RELIABLE_MAX = 14.7   # m/s² (~1.5g)
        
        # P_error Initialization
        INIT_P_POS = 0.01  # 1cm
        INIT_P_VEL = 0.001 # 1mm/s
        INIT_P_ORI_MIN = 1e-4
        INIT_P_ORI_MAX = 0.1
        INIT_P_GYRO_BIAS_MIN = 1e-6
        INIT_P_GYRO_BIAS_MAX = 1e-3
        INIT_P_ACCEL_BIAS_MIN = 1e-4
        INIT_P_ACCEL_BIAS_MAX = 1.0

        # Runtime Gating & Safety
        ACCEL_NORM_DIFF_MAX_CLAMP = 20.0  # m/s²
        MAHALANOBIS_MAX_CLAMP = 1e6       # Conservative safety limit
        S_MATRIX_REGULARIZATION = 1e-6    # For numerical stability (Cholesky)

        # Virtual Measurement Adaptive Scale
        VIRTUAL_MEAS_MAX_SCALE = 0.05
        VIRTUAL_MEAS_MIN_SCALE = 0.001

    # === Data Augmentation Noise ===
    class AUGMENTATION_NOISE:
        """Noise injection parameters for data augmentation."""
        # Gyroscope noise multiplier (relative to base noise)
        GYRO_NOISE_MULTIPLIER = 1.5
        # Accelerometer noise base level (m/s²)
        ACCEL_NOISE_BASE = 8.33e-3
        # Gyroscope noise base level (rad/s)
        GYRO_NOISE_BASE = 1.5e-3
        # Force sensor noise (arbitrary units)
        FORCE_NOISE_BASE = 0.5

    # === Data Preprocessing ===
    class PREPROCESSING:
        """Constants for data acquisition and preprocessing pipeline."""
        # Two-tap synchronization
        ROI_MARGIN_S = 1.0  # seconds - margin around writing region
        STATIC_BUFFER_S = 2.0  # seconds - static period before writing for initialization
        # Force thresholds for segmentation (iPad units)
        FORCE_THRESHOLD_START = 0.01
        FORCE_THRESHOLD_END = 0.01
        # Resampling and filtering
        MEDIAN_FILTER_WINDOW = 3  # samples
        SAVGOL_WINDOW = 11  # samples for Savitzky-Golay filter
        SAVGOL_POLYORDER = 3  # polynomial order for Savitzky-Golay

    # === Validation ===
    class VALIDATION:
        """Constants for model validation and metrics."""
        # Sequence length validation
        MIN_SEQUENCE_LENGTH = 10  # minimum valid sequence length (timesteps)
        MAX_SEQUENCE_LENGTH = 2000  # maximum sequence length before truncation
        # Tensor validation
        EXPECTED_SENSOR_CHANNELS = 7  # [accel_x, accel_y, accel_z, gyro_x, gyro_y, gyro_z, force]
        EXPECTED_SPATIAL_DIMS = 3  # [x, y, z] for positions and velocities