#pragma once

// Auto-generated by utils/export_model.py
// DO NOT EDIT - regenerate with: python utils/export_model.py

#include <cstdint>

namespace trajecto {

// TCN Architecture
constexpr int TCN_INPUT_SIZE = 16;
constexpr int TCN_NUM_LAYERS = 6;
constexpr float DT = 0.0199572914f;
constexpr int TCN_UPDATE_STRIDE = 4;

// State Buffer Dimensions {channels, history}
struct StateDim { int channels; int history; };
constexpr StateDim TCN_STATE_DIMS[] = {
    {16, 2},
    {96, 4},
    {96, 2},
    {96, 4},
    {96, 8},
    {96, 16},
};

// IMU Normalization (AccelXYZ, GyroXYZ, Force)
constexpr float IMU_MEAN[] = {2.91851636f, -8.09016939f, 4.23098800f, -0.01135616f, 0.00813827f, -0.00344270f, 956.41780222f};
constexpr float IMU_STD[] = {1.99539632f, 0.98817613f, 1.47147918f, 0.35205848f, 0.50353031f, 0.34035876f, 409.52650890f};

// Pen Tip Offset in Body Frame (x, y, z) meters
constexpr float PEN_TIP_OFFSET[] = {0.00000000f, -0.06000000f, 0.00000000f};

// Velocity Normalization (isotropic, from Python config)
constexpr float VEL_STD_L2 = 0.099435574329354f;
constexpr float VEL_CORRECTION_SCALE = 0.50000000f;

// Innovation Normalization (Allan variance based)
constexpr float MAX_VRW = 9.3271e-04f;  // max(VRW_X, VRW_Y, VRW_Z)
constexpr float MAX_ARW = 7.9283e-05f;  // max(ARW_X, ARW_Y, ARW_Z)
constexpr float INNOVATION_CLAMP_RANGE = 10.0f;

// Physical Constants
constexpr float GRAVITY_MAGNITUDE = 9.806650f;
constexpr float GRAVITY_NORM_SCALE = 2.0f;

// ESKF Parameters (from Config.ESKFTCN)
constexpr float ZUPT_NOISE_STD = 0.010000f;
constexpr float TCN_VEL_NOISE_STD = 0.050000f;
constexpr float MAHALANOBIS_GATE_THRESHOLD = 8.0f;
constexpr float ZUPT_HARD_RESET_THRESHOLD = 0.98f;
constexpr float ZUPT_PROB_THRESHOLD = 0.50f;
constexpr float R_MIN = 1.0e-04f;
constexpr float R_MAX = 3.00f;

// Motion & Initialization thresholds (from Config.MOTION)
constexpr float INIT_GYRO_VAR_THRESHOLD = 0.002000f;
constexpr float INIT_ACCEL_RELIABLE_MIN = 4.90f;
constexpr float INIT_ACCEL_RELIABLE_MAX = 14.70f;
constexpr float INIT_STATIC_MIN_S = 2.00f;
constexpr float ACCEL_NORM_DIFF_MAX_CLAMP = 20.00f;
constexpr float MAHALANOBIS_MAX_CLAMP = 1.0e+06f;
constexpr float S_MATRIX_REGULARIZATION = 1.0e-06f;
constexpr float VIRTUAL_MEAS_MAX_SCALE = 0.0500f;
constexpr float VIRTUAL_MEAS_MIN_SCALE = 0.0010f;

// Covariance Initialization constants
constexpr float INIT_P_POS = 0.0100f;
constexpr float INIT_P_VEL = 0.0010f;
constexpr float INIT_P_ORI_MAX = 0.1000f;
constexpr float INIT_P_GYRO_BIAS_MAX = 0.0010f;
constexpr float INIT_P_ACCEL_BIAS_MAX = 1.0000f;

// Allan Variance Noise Parameters (for ESKF Q matrix)
constexpr float VRW_X = 8.3297e-04f, VRW_Y = 6.7196e-04f, VRW_Z = 9.3271e-04f;
constexpr float ARW_X = 7.1664e-05f, ARW_Y = 7.9283e-05f, ARW_Z = 7.5335e-05f;
constexpr float GYRO_BI_X = 1.6441e-05f, GYRO_BI_Y = 2.8196e-05f, GYRO_BI_Z = 1.2203e-05f;
constexpr float ACCEL_BI_X = 4.3723e-04f, ACCEL_BI_Y = 1.7697e-04f, ACCEL_BI_Z = 2.8099e-04f;

} // namespace trajecto
