"""
This module provides a data acquisition system for collecting sensor and ground
truth data from a Trajecto device (e.g., smart pen) and an iPad application.

It manages the connection to the device, guides the user through a labeled
data collection process, and stores the acquired raw sensor data and corresponding
ground truth (from CSV files) into a structured HDF5 file. The system supports
resuming data collection by tracking global and iPad-specific sample counters.
"""

import asyncio
import os
import random
from typing import Any, Dict, List, Optional, Tuple

import h5py
import numpy as np
import pandas as pd

from receive import TrajectoDriver  # Assumes 'receive.py' is in the same directory.


# --- Constants ---
# Labels for continuous drawing shapes.
CONTINUOUS_SHAPES: List[str] = [
    "Infinity Loop (∞) - Keep drawing",
    "Spiral (In to Out) - Keep drawing",
    "Spiral (Out to In) - Keep drawing",
    "Zigzag (Continuous) - Keep drawing",
    "Random Scribble (Fast) - Keep drawing",
    "Random Scribble (Slow) - Keep drawing",
]
# Labels for discrete writing/drawing tasks (e.g., text sentences).
LOREM_SENTENCES: List[str] = [
    "lorem ipsum dolor sit amet",
    "consectetur adipiscing elit",
    "sed do eiusmod tempor incididunt",
    "ut labore et dolore magna aliqua",
    "ut enim ad minim veniam",
    "quis nostrud exercitation ullamco",
    "laboris nisi ut aliquip ex ea commodo",
    "duis aute irure dolor in reprehenderit",
    "voluptate velit esse cillum dolore",
    "eu fugiat nulla pariatur",
    "excepteur sint occaecat cupidatat",
    "sunt in culpa qui officia deserunt",
    "mollit anim id est laborum",
    "the quick brown fox jumps over the lazy dog",
    "pack my box with five dozen liquor jugs",
]
NUM_SESSIONS: int = 1  # Total number of data collection sessions to run.
DATA_DIR: str = "acquired_data"  # Directory to store raw CSVs and the HDF5 file.
HDF5_RAW_DATA_PATH: str = os.path.join(
    DATA_DIR, "raw_acquired_data.h5"
)  # Path for the HDF5 output file.


# --- Helper Functions ---
async def ainput(prompt: str = "") -> str:
    """Asynchronously gets user input, allowing non-blocking operation in asyncio loops.

    Args:
        prompt: The message to display to the user before waiting for input.

    Returns:
        The string entered by the user.
    """
    return await asyncio.get_event_loop().run_in_executor(None, lambda: input(prompt))


def generate_mixed_labels(num_labels: int) -> List[str]:
    """Generates a shuffled list of labels for data acquisition, mixing continuous
    shapes and Lorem Ipsum sentences.

    Args:
        num_labels: The total number of labels to generate.

    Returns:
        A shuffled list of strings, where each string is a label for a data sample.
    """
    scenario: List[str] = list(CONTINUOUS_SHAPES)
    remaining: int = num_labels - len(scenario)
    if remaining > 0:
        # Extend with random Lorem Ipsum sentences if more labels are needed.
        scenario.extend([random.choice(LOREM_SENTENCES) for _ in range(remaining)])
    else:
        # Truncate if fewer labels are needed than available continuous shapes.
        scenario = scenario[:num_labels]
    random.shuffle(scenario)  # Shuffle the labels to randomize acquisition order.
    return scenario


# --- Main Class ---
class DataAcquisition:
    """Manages the end-to-end process of acquiring sensor and ground truth data.

    This class handles device connection, user prompts, data buffering, and
    saving processed data to an HDF5 file, supporting session resumption.
    """

    def __init__(self, data_dir: str = DATA_DIR):
        """Initializes the DataAcquisition system.

        Args:
            data_dir: The directory where acquired data (e.g., GT CSVs) and
                the HDF5 output file will be stored.
        """
        self.data_dir: str = data_dir
        os.makedirs(self.data_dir, exist_ok=True)  # Ensure data directory exists.

        # Buffer to temporarily hold raw pen data received from the device for a single sample.
        self.pen_data_buffer: List[Dict[str, Any]] = []
        # Buffer to hold metadata and pen data for all samples collected within a session,
        # before final saving to HDF5.
        self.session_buffer: List[Dict[str, Any]] = []

        self.driver: Optional[TrajectoDriver] = None  # Instance of the device driver.
        self.hf_file: Optional[h5py.File] = None  # Handle for the HDF5 file.
        self.raw_data_group: Optional[h5py.Group] = None  # HDF5 group for raw data samples.

        # Counters for tracking samples.
        # `global_sample_counter` is an absolute index for samples in the HDF5 file.
        self.global_sample_counter: int = 0
        # `ipad_sample_counter` tracks the file number generated by the iPad app (e.g., Sample_1.csv).
        self.ipad_sample_counter: int = 1  # Default starting index for iPad files.

        print(f"Opening HDF5 file for raw data: {HDF5_RAW_DATA_PATH}")
        # Open HDF5 file in append mode ('a'). If it doesn't exist, it will be created.
        self.hf_file = h5py.File(HDF5_RAW_DATA_PATH, "a")
        # Ensure the 'raw_data' group exists within the HDF5 file.
        self.raw_data_group = self.hf_file.require_group("raw_data")

        # Resume Global Counter from HDF5:
        # This logic checks for existing samples in the HDF5 file to resume
        # `global_sample_counter` from the last saved sample, preventing overwrites.
        if len(self.raw_data_group.keys()) > 0:
            existing_sample_indices: List[int] = []
            for k in self.raw_data_group.keys():
                try:
                    # Extract numeric index from sample names like "sample_001", "sample_102".
                    num: int = int(k.split("_")[-1])
                    existing_sample_indices.append(num)
                except ValueError:
                    # Ignore keys that do not follow the naming convention.
                    continue

            if existing_sample_indices:
                # Set `global_sample_counter` to the maximum existing index, so the
                # next new sample will have `max_index + 1`.
                self.global_sample_counter = max(existing_sample_indices)
                print(
                    f"[Resume] Last saved sample index in HDF5: {self.global_sample_counter}"
                )
            else:
                print(
                    f"[Init] HDF5 exists but no valid samples found. Starting Global ID from 0."
                )
        else:
            print(f"[Init] New HDF5 file. Starting Global ID from 0.")

    async def setup_ipad_counter(self) -> None:
        """Asks the user for the current starting number displayed on the iPad app.

        This is crucial for synchronizing the global HDF5 sample index with
        the iPad's file naming convention (e.g., `Sample_1.csv`, `Sample_2.csv`).
        """
        print("\n" + "-" * 50)
        print(
            f"Global Database will start saving at: sample_{self.global_sample_counter + 1:03d}"
        )
        print("-" * 50)

        user_input: str = await ainput(
            f"What is the STARTING number displayed on the iPad? (Default 1): "
        )
        if user_input.strip().isdigit():
            self.ipad_sample_counter = int(user_input)
        else:
            self.ipad_sample_counter = 1  # Default to 1 if input is invalid.

        print(
            f"OK. Mapping logic: iPad 'Sample_{self.ipad_sample_counter}.csv' -> HDF5 'sample_{self.global_sample_counter + 1:03d}'\n"
        )

    def _pen_data_callback(self, data: Dict[str, Any]) -> None:
        """Callback function to receive and buffer pen data from the device driver.

        Args:
            data: A dictionary containing a single timestamped sensor reading.
        """
        self.pen_data_buffer.append(data)

    async def connect_device(self) -> bool:
        """Establishes connection with the Trajecto device.

        Returns:
            True if the connection is successful, False otherwise.
        """
        print("Initializing device connection...")
        self.driver = TrajectoDriver(data_callback=self._pen_data_callback)
        if await self.driver.connect():
            print("Device connected successfully.")
            return True
        print("Failed to connect to the device.")
        self.driver = None  # Reset driver if connection fails.
        return False

    async def disconnect_device(self) -> None:
        """Disconnects from the Trajecto device and closes the HDF5 file."""
        if self.driver:
            await self.driver.disconnect()
        print("Device disconnected.")
        if self.hf_file:
            self.hf_file.close()
            print(f"HDF5 file {HDF5_RAW_DATA_PATH} closed.")

    async def acquire_single_label(self, session_id: int, label: str, index: int, total: int) -> None:
        """Guides the user through acquiring a single labeled data sample.

        This method prompts the user, starts/stops data collection from the device,
        and handles user verification of the recording.

        Args:
            session_id: The ID of the current data collection session.
            label: The descriptive label for the current sample (e.g., "Infinity Loop").
            index: The current sample number within the session (1-indexed).
            total: The total number of samples to acquire in the current session.
        """
        if not self.driver:
            print("No device connected. Skipping acquisition.")
            return

        # Prepare global and iPad file indices for the current sample.
        current_global_idx: int = self.global_sample_counter + 1
        current_ipad_idx: int = self.ipad_sample_counter

        print(
            f"\n"
            + "=" * 60
            + f"\nTARGET: [{label}]\nProgress: ({index}/{total}) | iPad File: Sample_{current_ipad_idx}.csv\n"
            + "=" * 60
        )
        await ainput(">>> Press Enter when ready to start recording...")

        self.pen_data_buffer.clear()  # Clear buffer for new sample data.
        await self.driver.start_data_collection()  # Start receiving data from device.

        print("\nSTOP! Hold still on the paper for 2 seconds... (Calibrating)")
        await asyncio.sleep(2.0)  # Pause for a brief calibration period.
        print("GO! Start writing now.")
        await ainput("\n>>> Press Enter AFTER you finish writing.")  # Wait for user to finish task.
        await self.driver.stop_data_collection()  # Stop receiving data from device.

        verification: str = await ainput("Was the recording successful? (Y/n): ")
        if verification.lower() == "n":
            print(f"Label '{label}' marked as failed. Discarding pen data.")
            # Ask user if iPad still saved a file, to keep counters in sync.
            ipad_sync: str = await ainput(
                f"Did the iPad save 'Sample_{current_ipad_idx}.csv'? (y/N): "
            )
            if ipad_sync.lower() == "y":
                self.ipad_sample_counter += 1  # Increment to skip this iPad file number.
        else:
            # If successful, commit counters and add sample data to session buffer.
            self.global_sample_counter = current_global_idx
            self.ipad_sample_counter += 1  # Prepare for the next iPad file number.

            self.session_buffer.append(
                {
                    "session_id": session_id,
                    "global_idx": current_global_idx,  # Key for HDF5 group name.
                    "ipad_idx": current_ipad_idx,  # Key for finding corresponding GT CSV.
                    "label": label,
                    "pen_data": list(self.pen_data_buffer),  # Store a copy of buffered data.
                }
            )
            print(
                f"Sample captured. (Map: iPad {current_ipad_idx} -> Global {current_global_idx})"
            )

    async def process_and_save_session(self) -> None:
        """Processes all collected samples in the session buffer and saves them to HDF5.

        This involves converting buffered pen data to structured NumPy arrays,
        and loading corresponding ground truth data from CSV files generated
        by the iPad application.
        """
        if not self.session_buffer:
            print("No data in session buffer to save.")
            return

        print("\n" + "=" * 60)
        print(
            f"Session finished. Please move all GT CSV files for this session into the '{self.data_dir}' folder."
        )
        # Inform user which iPad files are expected to be present.
        print(
            f"Looking for files from Sample_{self.session_buffer[0]['ipad_idx']}.csv to Sample_{self.session_buffer[-1]['ipad_idx']}.csv"
        )
        await ainput(">>> Press Enter to continue and save all buffered data.")

        saved_count: int = 0
        for sample in self.session_buffer:
            pen_data: List[Dict[str, Any]] = sample["pen_data"]
            label: str = sample["label"]
            global_idx: int = sample["global_idx"]
            ipad_idx: int = sample["ipad_idx"]

            if not pen_data:
                print(f"No pen data for '{label}', skipping save.")
                continue

            # Create HDF5 group for the current sample using the global index.
            sample_group_name: str = f"sample_{global_idx:03d}"

            # If a group with this name already exists (e.g., from a previous failed run),
            # delete it to ensure a clean overwrite for this session's data.
            if self.raw_data_group and sample_group_name in self.raw_data_group:
                del self.raw_data_group[sample_group_name]

            if self.raw_data_group is None:
                raise RuntimeError("HDF5 raw data group is not initialized.")
            sample_group = self.raw_data_group.create_group(sample_group_name)

            # --- Save Sensor Data (pen_data) ---
            pen_keys: List[str] = list(pen_data[0].keys()) if pen_data else []
            # Determine data types for structured NumPy array based on first sample.
            pen_dtypes: List[Tuple[str, str]] = [
                (k, "f8")
                if isinstance(pen_data[0].get(k), (int, float))
                else (k, h5py.string_dtype())
                for k in pen_keys
            ]
            # Convert list of dicts to list of tuples for structured array creation.
            pen_data_tuples: List[Tuple[Any, ...]] = [
                tuple(d.get(k, None) for k in pen_keys) for d in pen_data
            ]
            pen_structured_array: np.ndarray = np.array(pen_data_tuples, dtype=pen_dtypes)
            sample_group.create_dataset("pen_data", data=pen_structured_array)

            # --- Find, Load, and Save Ground Truth Data ---
            gt_csv_path: str = os.path.join(self.data_dir, f"Sample_{ipad_idx}.csv")

            if os.path.exists(gt_csv_path):
                try:
                    df_gt: pd.DataFrame = pd.read_csv(gt_csv_path)
                    # Convert pandas DataFrame to structured NumPy array for HDF5 storage.
                    gt_structured_array: np.ndarray = df_gt.to_records(index=False)
                    sample_group.create_dataset("gt_data", data=gt_structured_array)
                    print(
                        f"  [Saved] Global {global_idx:03d} <== Sensor + iPad File 'Sample_{ipad_idx}.csv'"
                    )
                    saved_count += 1
                except Exception as e:
                    print(
                        f"  [ERROR] Failed to save GT data for '{label}' (File: Sample_{ipad_idx}.csv): {e}"
                    )
            else:
                print(
                    f"  [Warning] Missing GT File! Expected 'Sample_{ipad_idx}.csv' for Global {global_idx}. Only sensor data saved."
                )

            # Store metadata as HDF5 attributes.
            sample_group.attrs["original_label"] = label
            sample_group.attrs["session_id"] = sample["session_id"]
            sample_group.attrs["ipad_file_index"] = (
                ipad_idx  # Record original iPad index for debugging/tracing.
            )

        print(f"\nSaved {saved_count} complete samples to HDF5.")
        self.session_buffer.clear()  # Clear buffer after saving.


async def main() -> None:
    """Main function to run the Trajecto Data Acquisition System."""
    print("--- Trajecto Data Acquisition System (Resume Supported) ---")
    print("Guidelines: Hold still on start, write continuously, keep sensor rigid.")

    num_labels_per_session: int = 9
    acquisition_system: DataAcquisition = DataAcquisition()

    await acquisition_system.setup_ipad_counter()

    try:
        for session_id in range(NUM_SESSIONS):
            print(f"\n--- Preparing for Session {session_id} ---")
            if not await acquisition_system.connect_device():
                print("Aborting program due to connection failure.")
                break

            labels_to_acquire: List[str] = generate_mixed_labels(
                num_labels=num_labels_per_session
            )

            for i, label in enumerate(labels_to_acquire):
                await acquisition_system.acquire_single_label(
                    session_id, label, i + 1, len(labels_to_acquire)
                )

            await acquisition_system.process_and_save_session()

            # Prompt user to continue to the next session if there are more.
            if session_id < NUM_SESSIONS - 1:
                cont: str = await ainput("\nSession finished. Continue to next session? (y/n): ")
                if cont.lower() != "y":
                    break
    finally:
        # Ensure device is disconnected and HDF5 file is closed even if errors occur.
        await acquisition_system.disconnect_device()

    print("\n--- Data Acquisition Finished ---")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nAcquisition interrupted by user. Exiting.")
        # Optionally, add graceful shutdown for the acquisition_system here
        # if it's accessible and needs to close files/connections.