# Trajecto: Real-time 3D Trajectory Reconstruction System (Software)
# Copyright 2025-2026 Eunkyum Kim <nemonanconcode@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# NOTICE: This software implements the "Hybrid ESKF-Stateful TCN" logic 
# protected under ROK Patent Application No. 10-2025-YYYYYYY.
# Commercial use requires a separate license from the author.

#!/usr/bin/env python3
"""
Compute velocity statistics needed for Config.

This script computes:
1. Velocity statistics (mean, std per-axis, L2 norm)
2. Derived isotropic correction scale (2σ coverage)

Innovation normalization uses Allan variance (VRW/ARW) from config.py,
NOT empirical statistics (which are contaminated by ESKF drift).

Run this script whenever you:
- Add new training data
- Change data preprocessing
- Want to update model configuration

Usage:
    python utils/compute_config_statistics.py

Output:
    Prints Python code to paste into model/config.py
"""

import os
import sys
from typing import Dict

import h5py
import numpy as np

# Add parent directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from model.config import Config


def compute_velocity_statistics(
    dataset_path: str = "./data/dataset.h5",
    num_samples: int = 100
) -> Dict[str, np.ndarray]:
    """Compute velocity statistics from ground truth data.

    Args:
        dataset_path: Path to HDF5 dataset
        num_samples: Number of samples to use for statistics

    Returns:
        Dictionary with vel_mean, vel_std, vel_std_l2
    """
    print("="*70)
    print("COMPUTING VELOCITY STATISTICS")
    print("="*70)

    if not os.path.exists(dataset_path):
        raise FileNotFoundError(f"Dataset not found: {dataset_path}")

    with h5py.File(dataset_path, 'r') as f:
        # Get sample keys that have velocity data
        sample_keys = [k for k in list(f.keys()) if 'gt_vel_data' in f[k]][:num_samples]

        if not sample_keys:
            raise ValueError("No samples with 'gt_vel_data' found in dataset")

        print(f"Processing {len(sample_keys)} samples...")

        all_vels = []
        for i, key in enumerate(sample_keys):
            vel = f[key]['gt_vel_data'][:]
            all_vels.append(vel)

            if (i + 1) % 20 == 0:
                print(f"  Processed {i + 1}/{len(sample_keys)} samples")

        # Concatenate and compute statistics
        all_vels = np.concatenate(all_vels, axis=0)
        vel_mean = np.mean(all_vels, axis=0)
        vel_std = np.std(all_vels, axis=0)
        vel_std_l2 = np.sqrt(np.sum(vel_std**2))

        # Compute additional statistics for reporting
        vel_mag = np.linalg.norm(all_vels, axis=1)

        print(f"\nTotal timesteps: {len(all_vels)}")
        print(f"Velocity Mean: {vel_mean} m/s")
        print(f"Velocity Std:  {vel_std} m/s")
        print(f"Velocity Std L2: {vel_std_l2:.6f} m/s")
        print(f"\nVelocity Magnitude Statistics:")
        print(f"  Mean: {np.mean(vel_mag):.4f} m/s")
        print(f"  50th: {np.percentile(vel_mag, 50):.4f} m/s")
        print(f"  95th: {np.percentile(vel_mag, 95):.4f} m/s")
        print(f"  99th: {np.percentile(vel_mag, 99):.4f} m/s")
        print(f"  Max:  {np.max(vel_mag):.4f} m/s")

        return {
            'vel_mean': vel_mean,
            'vel_std': vel_std,
            'vel_std_l2': vel_std_l2
        }


def format_for_config(vel_stats: Dict[str, np.ndarray]) -> str:
    """Format computed statistics as Python code for config.py.

    Args:
        vel_stats: Velocity statistics dictionary

    Returns:
        Formatted Python code string
    """
    vel_std_l2 = vel_stats['vel_std_l2']

    code = f'''
# =============================================================================
# COMPUTED STATISTICS (Generated by utils/compute_config_statistics.py)
# =============================================================================
# To regenerate: python utils/compute_config_statistics.py
# Dataset: data/dataset.h5
# =============================================================================

# --- Velocity Statistics (from ground truth) ---
# L2 norm of per-axis velocity std, used for isotropic body-frame normalization
VEL_STD_L2 = {vel_std_l2:.15f}  # m/s
'''

    return code


def main():
    """Main function to compute all statistics."""
    print("\n" + "="*70)
    print("TRAJECTO CONFIG STATISTICS COMPUTATION")
    print("="*70)
    print("\nThis script computes velocity statistics for model/config.py")
    print("Note: Innovation normalization uses Allan variance (VRW/ARW)")
    print("Estimated time: 5-10 seconds\n")

    try:
        # Compute velocity statistics
        vel_stats = compute_velocity_statistics(
            dataset_path="./data/dataset.h5",
            num_samples=100
        )

        # Display Allan variance info (innovation normalization)
        print("\n" + "="*70)
        print("INNOVATION NORMALIZATION (Allan Variance)")
        print("="*70)
        print("Using theoretical measurement noise from Allan variance analysis:")
        print(f"  VRW (accel): [{Config.VRW_X:.6f}, {Config.VRW_Y:.6f}, {Config.VRW_Z:.6f}] m/s²")
        print(f"  ARW (gyro):  [{Config.ARW_X:.8f}, {Config.ARW_Y:.8f}, {Config.ARW_Z:.8f}] rad/s")
        print("\nThese values are used for isotropic innovation normalization:")
        max_vrw = max(Config.VRW_X, Config.VRW_Y, Config.VRW_Z)
        max_arw = max(Config.ARW_X, Config.ARW_Y, Config.ARW_Z)
        print(f"  Accel (all axes): / {max_vrw:.6f} m/s²")
        print(f"  Gyro (all axes):  / {max_arw:.8f} rad/s")

        # Format for config.py
        config_code = format_for_config(vel_stats)

        # Print results
        print("\n" + "="*70)
        print("SUCCESS! Copy the following into model/config.py:")
        print("="*70)
        print(config_code)

        # Save to file
        output_file = "config_statistics.txt"
        with open(output_file, 'w') as f:
            f.write(config_code)
        print(f"\n✓ Saved to {output_file}")

        # Summary
        print("\n" + "="*70)
        print("SUMMARY")
        print("="*70)
        print(f"Velocity std L2:          {vel_stats['vel_std_l2']:.4f} m/s")
        print(f"Per-axis X/Y/Z std:       {vel_stats['vel_std'][0]:.4f}, {vel_stats['vel_std'][1]:.4f}, {vel_stats['vel_std'][2]:.4f} m/s (diagnostic only)")
        print(f"\nInnovation normalization: Allan variance (theoretical)")
        print(f"  Max VRW (accel):        {max_vrw:.6f} m/s²")
        print(f"  Max ARW (gyro):         {max_arw:.8f} rad/s")

    except Exception as e:
        print(f"\n❌ ERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
