#pragma once

// Auto-generated by utils/export_model.py
// DO NOT EDIT - regenerate with: python utils/export_model.py

#include <cstdint>

namespace trajecto {

// TCN Architecture
constexpr int TCN_INPUT_SIZE = 19;  // Reduced from 20: removed zupt_flag to avoid circular dependency
constexpr int TCN_NUM_LAYERS = 4;
constexpr float DT = 0.019957245f;  // 50.107 Hz measured from stationary data
constexpr int TCN_UPDATE_STRIDE = 4;  // Run TCN every N timesteps (12.5Hz at 50Hz base)

// State Buffer Dimensions {channels, history}
struct StateDim { int channels; int history; };
constexpr StateDim TCN_STATE_DIMS[] = {
    { 19, 2 },  // First layer input matches TCN_INPUT_SIZE
    { 64, 4 },
    { 64, 8 },
    { 64, 16 },
};

// IMU Normalization (AccelXYZ, GyroXYZ, Force)
constexpr float IMU_MEAN[] = {2.78230069f, -2.68209409f, 4.19848411f, -0.16821001f, 0.33020652f, 0.23807174f, 3830.24641663f};
constexpr float IMU_STD[] = {5.81654358f, 5.70299290f, 1.71116575f, 37.63273751f, 39.02173354f, 27.56065179f, 597.15314685f};

// Pen Tip Offset in Body Frame (x, y, z) meters
constexpr float PEN_TIP_OFFSET[] = {0.0f, -0.06f, 0.0f};

// Velocity Normalization (isotropic, from Python config)
constexpr float VEL_STD_L2 = 0.152273716759559f;
constexpr float VEL_CORRECTION_SCALE = 0.50000000f;

// Innovation Normalization (Allan variance based)
constexpr float MAX_VRW = 9.3271e-04f;  // max(VRW_X, VRW_Y, VRW_Z)
constexpr float MAX_ARW = 7.9283e-05f;  // max(ARW_X, ARW_Y, ARW_Z)
constexpr float INNOVATION_CLAMP_RANGE = 10.0f;

// Physical Constants
constexpr float GRAVITY_MAGNITUDE = 9.80665f;
constexpr float GRAVITY_NORM_SCALE = 2.0f;

// ESKF Parameters (from Config.ESKFTCN - centralized config)
constexpr float ZUPT_NOISE_STD = 0.010000f;
constexpr float TCN_VEL_NOISE_STD = 0.050000f;
constexpr float MAHALANOBIS_GATE_THRESHOLD = 8.0f;
constexpr float ZUPT_HARD_RESET_THRESHOLD = 0.98f;

// Allan Variance Noise Parameters (for ESKF Q matrix)
constexpr float VRW_X = 8.3297e-04f, VRW_Y = 6.7196e-04f, VRW_Z = 9.3271e-04f;
constexpr float ARW_X = 7.1664e-05f, ARW_Y = 7.9283e-05f, ARW_Z = 7.5335e-05f;
constexpr float GYRO_BI_X = 1.6441e-05f, GYRO_BI_Y = 2.8196e-05f, GYRO_BI_Z = 1.2203e-05f;
constexpr float ACCEL_BI_X = 4.3723e-04f, ACCEL_BI_Y = 1.7697e-04f, ACCEL_BI_Z = 2.8099e-04f;

} // namespace trajecto
