#pragma once

// Auto-generated by export_onnx.py
#include <vector>

namespace trajecto {

    constexpr int TCN_INPUT_SIZE = 20;
    constexpr int TCN_NUM_LAYERS = 4;
    constexpr float DT = 0.019957245f; // 50.107 Hz measured from stationary data

    // State Buffer Dimensions {Channels, HistoryLength}
    struct StateDim { int channels; int history; };
    constexpr StateDim TCN_STATE_DIMS[] = {
        { 20, 2 },
        { 64, 4 },
        { 64, 8 },
        { 64, 16 },
    };

    // IMU Normalization Parameters (AccelX, AccelY, AccelZ, GyroX, GyroY, GyroZ, Force)
    constexpr float IMU_MEAN[] = {2.78230069f, -2.68209409f, 4.19848411f, -0.16821001f, 0.33020652f, 0.23807174f, 3830.24641663f};
    constexpr float IMU_STD[] = {5.81654358f, 5.70299290f, 1.71116575f, 37.63273751f, 39.02173354f, 27.56065179f, 597.15314685f};

    // Pen Tip Offset in Body Frame (x, y, z)
    constexpr float PEN_TIP_OFFSET[] = {0.00000000f, 0.00000000f, 0.00000000f};

} // namespace trajecto
