#include "eskf.hpp"
#include "model_params.hpp"
#include <iostream>
#include <cmath>
#include <algorithm>

namespace trajecto {

ESKF::ESKF(float dt) : dt_(dt) {
    P_.setIdentity();
    P_ *= 0.1f;

    // Process noise from Allan Variance analysis (from model_params.hpp, generated by export_model.py)
    // VRW: Velocity Random Walk (accel noise) - m/s²/√Hz
    // ARW: Angular Random Walk (gyro noise) - rad/√Hz
    // Bias Instability: long-term drift parameters
    Q_diag_.setZero();
    // Position noise: driven by velocity (set to 0)
    Q_diag_.segment<3>(0).setZero();
    // Velocity noise: from accelerometer VRW
    Q_diag_(3) = VRW_X * VRW_X;
    Q_diag_(4) = VRW_Y * VRW_Y;
    Q_diag_(5) = VRW_Z * VRW_Z;
    // Orientation noise: from gyroscope ARW
    Q_diag_(6) = ARW_X * ARW_X;
    Q_diag_(7) = ARW_Y * ARW_Y;
    Q_diag_(8) = ARW_Z * ARW_Z;
    // Gyro bias drift: from bias instability
    Q_diag_(9) = GYRO_BI_X * GYRO_BI_X;
    Q_diag_(10) = GYRO_BI_Y * GYRO_BI_Y;
    Q_diag_(11) = GYRO_BI_Z * GYRO_BI_Z;
    // Accel bias drift: from bias instability
    Q_diag_(12) = ACCEL_BI_X * ACCEL_BI_X;
    Q_diag_(13) = ACCEL_BI_Y * ACCEL_BI_Y;
    Q_diag_(14) = ACCEL_BI_Z * ACCEL_BI_Z;

    // ESKF noise parameters (from model_params.hpp - centralized config)
    zupt_noise_std_ = ZUPT_NOISE_STD;
    tcn_vel_noise_std_ = TCN_VEL_NOISE_STD;

    // Gravity in world frame: Z points UP, gravity pulls DOWN (negative Z)
    // This matches Python: gravity_w = [0, 0, -GRAVITY_MAGNITUDE]
    gravity_w_ << 0.0f, 0.0f, -GRAVITY_MAGNITUDE;

    // Mahalanobis gating threshold (from model_params.hpp - matches Python config)
    mahalanobis_gate_threshold_ = MAHALANOBIS_GATE_THRESHOLD;
}

void ESKF::initialize(const Eigen::Vector3f& accel_init) {
    // When stationary, accelerometer measures reaction to gravity: -g_world in body frame
    // With gravity_w = [0, 0, -9.81], if device is flat, accel reads [0, 0, +9.81]
    // We need to find quaternion q such that: q * accel_body = gravity_w
    // i.e., rotate body frame to align with world frame where gravity points -Z
    Eigen::Vector3f accel_norm = accel_init.normalized();
    Eigen::Vector3f gravity_dir = -Eigen::Vector3f::UnitZ();  // Gravity direction in world: -Z

    // FromTwoVectors(a, b) gives quaternion that rotates a to b
    // Here: rotate accel reading (which is -gravity_body) to align with -Z world
    // accel measures -g_body, so we rotate -accel_norm to gravity_dir
    Eigen::Quaternionf q_init = Eigen::Quaternionf::FromTwoVectors(-accel_norm, gravity_dir);

    state_.quat = q_init;
    state_.pos.setZero();
    state_.vel.setZero();
    state_.gyro_bias.setZero();
    state_.accel_bias.setZero();

    P_.setIdentity();
    P_ *= 0.1f;
}

void ESKF::predict(const Eigen::Vector3f& gyro_raw, const Eigen::Vector3f& accel_raw) {
    Eigen::Vector3f gyro_corrected = gyro_raw - state_.gyro_bias;
    Eigen::Vector3f accel_corrected = accel_raw - state_.accel_bias;

    Eigen::Matrix3f R_bw = state_.quat.toRotationMatrix();

    Eigen::Vector3f accel_w = R_bw * accel_corrected - gravity_w_;

    state_.pos += state_.vel * dt_ + 0.5f * accel_w * dt_ * dt_;

    state_.vel += accel_w * dt_;

    Eigen::Vector3f omega = gyro_corrected * dt_;
    float angle = omega.norm();
    Eigen::Quaternionf q_delta;
    if (angle > 1e-8f) {
        q_delta = Eigen::Quaternionf(Eigen::AngleAxisf(angle, omega / angle));
    } else {
        q_delta = Eigen::Quaternionf::Identity();
    }
    state_.quat = state_.quat * q_delta;
    state_.quat.normalize();

    Eigen::Matrix<float, STATE_DIM, STATE_DIM> F;
    F.setIdentity();

    F.block<3, 3>(0, 3) = Eigen::Matrix3f::Identity() * dt_;

    Eigen::Matrix3f accel_skew;
    accel_skew << 0, -accel_corrected.z(), accel_corrected.y(),
                  accel_corrected.z(), 0, -accel_corrected.x(),
                  -accel_corrected.y(), accel_corrected.x(), 0;
    F.block<3, 3>(3, 6) = -R_bw * accel_skew * dt_;

    F.block<3, 3>(3, 12) = -R_bw * dt_;

    F.block<3, 3>(6, 9) = -Eigen::Matrix3f::Identity() * dt_;

    Eigen::Matrix<float, STATE_DIM, STATE_DIM> Q;
    Q.setZero();
    Q.diagonal() = Q_diag_ * dt_;

    P_ = F * P_ * F.transpose() + Q;
    
    enforce_symmetry();
}

void ESKF::update_zupt(float prob) {
    Eigen::Matrix<float, 3, STATE_DIM> H;
    H.setZero();
    H.block<3, 3>(0, 3).setIdentity();

    Eigen::Matrix3f R;
    R.setIdentity();

    if (prob >= 0.0f) {
        float min_R_val = zupt_noise_std_ * zupt_noise_std_;
        float max_R_val = min_R_val * 100.0f;
        float clamped_prob = std::max(0.01f, std::min(prob, 0.99f));
        
        float r_val = min_R_val * clamped_prob + max_R_val * (1.0f - clamped_prob);
        R.diagonal().setConstant(r_val);
    } else {
        R *= (zupt_noise_std_ * zupt_noise_std_);
    }

    Eigen::Vector3f innovation = -state_.vel;

    Eigen::Matrix<float, STATE_DIM, 3> PHt = P_ * H.transpose();
    Eigen::Matrix3f S = H * PHt + R;
    Eigen::Matrix<float, STATE_DIM, 3> K = PHt * S.inverse();

    Eigen::Matrix<float, STATE_DIM, 1> delta_x = K * innovation;

    Eigen::Matrix<float, STATE_DIM, STATE_DIM> I = Eigen::Matrix<float, STATE_DIM, STATE_DIM>::Identity();
    P_ = (I - K * H) * P_;
    
    enforce_symmetry();
    inject_error(delta_x);
}

void ESKF::update_tcn_vel(const Eigen::Vector3f& vel_corr_body, const Eigen::Matrix<float, 6, 1>& R_params) {
    Eigen::Matrix3f R_bw = state_.quat.toRotationMatrix();
    Eigen::Vector3f vel_corr_w = R_bw * vel_corr_body;

    Eigen::Matrix<float, 3, STATE_DIM> H;
    H.setZero();
    H.block<3, 3>(0, 3).setIdentity();

    // Use TCN's adaptive R matrix (first 3 elements of R_params)
    // Python applies: R_vel_diag = softplus(tcn_cov_raw[:, :3]) + 1e-4, clamped to [1e-4, 3.0]
    Eigen::Matrix3f R;
    R.setZero();
    for (int i = 0; i < 3; i++) {
        float val = R_params[i];
        // Apply softplus: log(1 + exp(x))
        float softplus_val = (val > 20.0f) ? val : std::log1p(std::exp(val));
        // Add floor and clamp to valid range
        float R_val = softplus_val + 1e-4f;
        R_val = std::max(1e-4f, std::min(3.0f, R_val));
        R(i, i) = R_val;
    }

    Eigen::Vector3f innovation = vel_corr_w;

    Eigen::Matrix<float, STATE_DIM, 3> PHt = P_ * H.transpose();
    Eigen::Matrix3f S = H * PHt + R;
    Eigen::Matrix<float, STATE_DIM, 3> K = PHt * S.inverse();

    Eigen::Matrix<float, STATE_DIM, 1> delta_x = K * innovation;

    // Joseph form for numerical stability (matches Python)
    Eigen::Matrix<float, STATE_DIM, STATE_DIM> I = Eigen::Matrix<float, STATE_DIM, STATE_DIM>::Identity();
    Eigen::Matrix<float, STATE_DIM, STATE_DIM> ImKH = I - K * H;
    P_ = ImKH * P_ * ImKH.transpose() + K * R * K.transpose();

    enforce_symmetry();
    inject_error(delta_x);
}

Eigen::Matrix<float, 6, 1> ESKF::update_imu(
    const Eigen::Vector3f& accel_raw,
    const Eigen::Vector3f& gyro_raw,
    const Eigen::Matrix<float, 6, 1>& R_diag,
    float* out_mahalanobis
) {
    Eigen::Matrix<float, 6, STATE_DIM> H;
    H.setZero();

    Eigen::Matrix3f R_bw = state_.quat.toRotationMatrix();
    Eigen::Matrix3f R_wb = R_bw.transpose();
    Eigen::Vector3f g_body = R_wb * gravity_w_;

    Eigen::Matrix3f g_skew;
    g_skew << 0, -g_body.z(), g_body.y(),
              g_body.z(), 0, -g_body.x(),
              -g_body.y(), g_body.x(), 0;

    H.block<3, 3>(0, 6) = g_skew;
    H.block<3, 3>(0, 12).setIdentity();

    H.block<3, 3>(3, 9).setIdentity();

    Eigen::Vector3f accel_pred = g_body + state_.accel_bias;
    Eigen::Vector3f gyro_pred = state_.gyro_bias;

    Eigen::Matrix<float, 6, 1> innovation;
    innovation.segment<3>(0) = accel_raw - accel_pred;
    innovation.segment<3>(3) = gyro_raw - gyro_pred;

    Eigen::Matrix<float, 6, 6> R;
    R.setZero();
    R.diagonal() = R_diag;
    R.diagonal().array() += 1e-6f;

    Eigen::Matrix<float, STATE_DIM, 6> PHt = P_ * H.transpose();
    Eigen::Matrix<float, 6, 6> S = H * PHt + R;

    Eigen::Matrix<float, 6, 1> S_inv_y = S.ldlt().solve(innovation);
    float mahalanobis_sq = innovation.dot(S_inv_y);

    if (out_mahalanobis) {
        *out_mahalanobis = mahalanobis_sq;
    }

    if (mahalanobis_sq > mahalanobis_gate_threshold_) {
        return innovation;
    }

    Eigen::Matrix<float, STATE_DIM, 6> K = PHt * S.inverse();

    Eigen::Matrix<float, STATE_DIM, 1> delta_x = K * innovation;

    Eigen::Matrix<float, STATE_DIM, STATE_DIM> I = Eigen::Matrix<float, STATE_DIM, STATE_DIM>::Identity();
    P_ = (I - K * H) * P_;

    enforce_symmetry();
    inject_error(delta_x);

    return innovation;
}

bool ESKF::check_zupt(const Eigen::Vector3f& accel_raw) {
    float norm = accel_raw.norm();
    return std::abs(norm - GRAVITY_MAGNITUDE) < 0.3f;
}

void ESKF::hard_reset_velocity() {
    // Directly set velocity to zero (matches Python ESKF.py:901-908)
    // Used when TCN is very confident about stationary state (zupt_prob >= 0.98)
    state_.vel.setZero();
}

void ESKF::inject_error(const Eigen::Matrix<float, STATE_DIM, 1>& delta_x) {
    Eigen::Vector3f d_pos = delta_x.segment<3>(0);
    Eigen::Vector3f d_vel = delta_x.segment<3>(3);
    Eigen::Vector3f d_theta = delta_x.segment<3>(6);
    Eigen::Vector3f d_bg = delta_x.segment<3>(9);
    Eigen::Vector3f d_ba = delta_x.segment<3>(12);

    state_.pos += d_pos;
    state_.vel += d_vel;
    state_.gyro_bias += d_bg;
    state_.accel_bias += d_ba;

    Eigen::Quaternionf q_delta;
    q_delta.w() = 1.0f;
    q_delta.vec() = 0.5f * d_theta;
    q_delta.normalize();

    state_.quat = state_.quat * q_delta;
    state_.quat.normalize();
}

void ESKF::enforce_symmetry() {
    P_ = 0.5f * (P_ + P_.transpose());
}

} // namespace trajecto
