#include "tcn_wrapper.hpp"
#include "fast_math_lut.hpp"
#include <cmath>
#include <algorithm>
#include <iostream>
#include <cstring>

#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/system_setup.h"
#include "tensorflow/lite/schema/schema_generated.h"

// External reference to the model data (generated by generate_cc_model.py)
// Aligned to 16 bytes in the generated file.
extern const unsigned char tcn_model_tflite[];
extern const unsigned int tcn_model_tflite_len;

namespace trajecto {

TCNWrapper::TCNWrapper() {}

TCNWrapper::~TCNWrapper() {
    if (interpreter_) delete interpreter_;
    if (tensor_arena_) delete[] tensor_arena_;
}

bool TCNWrapper::setup() {
    // 1. Load Model
    model_ = tflite::GetModel(tcn_model_tflite);
    if (model_->version() != TFLITE_SCHEMA_VERSION) {
        std::cerr << "Model schema version mismatch!" << std::endl;
        return false;
    }

    // 2. Resolver
    static tflite::MicroMutableOpResolver<11> resolver;
    resolver.AddConv2D();
    resolver.AddDepthwiseConv2D(); // Enabled for Depthwise Separable TCN
    resolver.AddFullyConnected();
    resolver.AddReshape();
    resolver.AddSoftmax();
    resolver.AddLogistic(); // Sigmoid
    resolver.AddTanh();
    resolver.AddRelu();
    resolver.AddAdd();
    resolver.AddMul();
    resolver.AddConcatenation();

    // 3. Tensor Arena
    tensor_arena_ = new uint8_t[kTensorArenaSize];

    // 4. Interpreter
    static tflite::MicroInterpreter static_interpreter(
        model_, resolver, tensor_arena_, kTensorArenaSize);
    interpreter_ = &static_interpreter;

    // 5. Allocate Tensors
    if (interpreter_->AllocateTensors() != kTfLiteOk) {
        std::cerr << "AllocateTensors failed!" << std::endl;
        return false;
    }

    // 6. Initialize State Buffers (Zeros)
    state_buffers_.resize(TCN_NUM_LAYERS);
    for (int i = 0; i < TCN_NUM_LAYERS; i++) {
        int size = TCN_STATE_DIMS[i].channels * TCN_STATE_DIMS[i].history;
        state_buffers_[i].assign(size, 0.0f);
    }

    return true;
}

void TCNWrapper::extract_features(
    const Eigen::Vector3f& accel_raw,
    const Eigen::Vector3f& gyro_raw,
    float force_raw,
    const ESKF& eskf,
    const Eigen::Matrix<float, 6, 1>& last_innovation,
    bool is_zupt,
    std::vector<float>& out_features
) {
    out_features.resize(kInputSize);
    const auto& state = eskf.get_state();

    float norm_accel[3];
    float norm_gyro[3];
    float norm_force;

    for (int i = 0; i < 3; i++) norm_accel[i] = (accel_raw[i] - IMU_MEAN[i]) / IMU_STD[i];
    for (int i = 0; i < 3; i++) norm_gyro[i] = (gyro_raw[i] - IMU_MEAN[i + 3]) / IMU_STD[i + 3];
    norm_force = (force_raw - IMU_MEAN[6]) / IMU_STD[6];

    Eigen::Matrix3f R_bw = state.quat.toRotationMatrix();
    Eigen::Vector3f gravity_b = R_bw.transpose() * Eigen::Vector3f::UnitZ();
    
    Eigen::Vector3f vel_b_linear = R_bw.transpose() * state.vel;
    
    Eigen::Vector3f gyro_corr = gyro_raw - state.gyro_bias;
    Eigen::Vector3f offset;
    offset << PEN_TIP_OFFSET[0], PEN_TIP_OFFSET[1], PEN_TIP_OFFSET[2];
    Eigen::Vector3f vel_tangential = gyro_corr.cross(offset);
    
    Eigen::Vector3f pen_tip_vel_b = vel_b_linear + vel_tangential;
    
    // Using std::tanh for now as we focused on exp/sigmoid LUT.
    for (int i=0; i<3; i++) pen_tip_vel_b[i] = std::tanh(pen_tip_vel_b[i]);

    Eigen::Matrix<float, 6, 1> inn_squashed;
    for (int i=0; i<6; i++) inn_squashed[i] = std::tanh(last_innovation[i]);

    int idx = 0;
    out_features[idx++] = norm_gyro[0];
    out_features[idx++] = norm_gyro[1];
    out_features[idx++] = norm_gyro[2];
    out_features[idx++] = norm_accel[0];
    out_features[idx++] = norm_accel[1];
    out_features[idx++] = norm_accel[2];
    out_features[idx++] = norm_force;
    out_features[idx++] = pen_tip_vel_b[0];
    out_features[idx++] = pen_tip_vel_b[1];
    out_features[idx++] = pen_tip_vel_b[2];
    out_features[idx++] = gravity_b[0];
    out_features[idx++] = gravity_b[1];
    out_features[idx++] = gravity_b[2];
    // Note: zupt_flag removed to avoid circular dependency (TCN predicts zupt_prob)
    for (int i=0; i<6; i++) out_features[idx++] = inn_squashed[i];
}

TCNOutput TCNWrapper::process_step(
    const Eigen::Vector3f& accel_raw,
    const Eigen::Vector3f& gyro_raw,
    float force_raw,
    const ESKF& eskf,
    const Eigen::Matrix<float, 6, 1>& last_innovation,
    bool is_zupt
) {
    TCNOutput result;
    result.valid = true; // Always valid with stateful

    // 1. Extract Features
    std::vector<float> features;
    extract_features(accel_raw, gyro_raw, force_raw, eskf, last_innovation, is_zupt, features);

    // 2. Set Input 0 (Feature)
    TfLiteTensor* input_feat = interpreter_->input(0);
    // Shape: [1, 1, 20] or similar. Just copy flat data.
    std::memcpy(input_feat->data.f, features.data(), features.size() * sizeof(float));

    // 3. Set Inputs 1..N (States)
    for (int i = 0; i < TCN_NUM_LAYERS; i++) {
        TfLiteTensor* input_state = interpreter_->input(1 + i);
        std::memcpy(input_state->data.f, state_buffers_[i].data(), state_buffers_[i].size() * sizeof(float));
    }

    // 4. Run Inference
    if (!interpreter_) {
        // Fail silently or error? Error preferred.
        // std::cerr << "Interpreter not initialized!" << std::endl;
        result.valid = false;
        return result;
    }

    if (interpreter_->Invoke() != kTfLiteOk) {
        std::cerr << "Invoke failed!" << std::endl;
        result.valid = false;
        return result;
    }

    // 5. Read Outputs 0..2 (Predictions)
    // Indices: 0->vel_corr, 1->cov_R, 2->zupt_prob
    TfLiteTensor* out_vel = interpreter_->output(0);
    TfLiteTensor* out_cov = interpreter_->output(1);
    TfLiteTensor* out_zupt = interpreter_->output(2);

    result.vel_corr[0] = out_vel->data.f[0];
    result.vel_corr[1] = out_vel->data.f[1];
    result.vel_corr[2] = out_vel->data.f[2];

    for(int i=0; i<6; i++) result.R_params[i] = out_cov->data.f[i];

    float zupt_logit = out_zupt->data.f[0];
    // Optimized: Use Fast Sigmoid LUT
    result.zupt_prob = fast_sigmoid(zupt_logit);

    // 6. Read Outputs 3..M (New States) and Update Buffers
    for (int i = 0; i < TCN_NUM_LAYERS; i++) {
        TfLiteTensor* out_state = interpreter_->output(3 + i);
        // Copy back to persistence buffer
        std::memcpy(state_buffers_[i].data(), out_state->data.f, state_buffers_[i].size() * sizeof(float));
    }

    return result;
}

} // namespace trajecto